version: '3.4'

services:
  api:
    image: ticket-reservation:latest
    volumes:
      - ./config_docker.yml:/config.yaml:ro
      - ../_dev_server_keys:/server_keys:ro
    entrypoint:
      [
          '/wait-for-it.sh',
          'postgres:5432',
          '--',
          '/ticket-reservation',
          '--config=/config.yaml',
          'serve-api',
      ]
    #    ports: # can't use this with --scale
    #      - 9092:9092
    depends_on:
      - postgres
      - db-init
    networks:
      - ticket-reservation
    restart: unless-stopped
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ticket_reservation}
    #volumes:
     # - ../postgres_data:/var/lib/postgresql/data # for data persistence
    security_opt:
      - no-new-privileges
    ports:
      - 5432:${POSTGRES_PORT:-5432}
    networks:
      - ticket-reservation
    restart: unless-stopped
  db-init:
    image: ticket-reservation:latest
    volumes:
      - ./config_docker.yml:/config.yaml:ro
      - ../_dev_server_keys:/server_keys:ro
    entrypoint:
      [
          '/wait-for-it.sh',
          'postgres:5432',
          '--',
          '/ticket-reservation',
          '--config=/config.yaml',
          'migrate-db',
      ]
    depends_on:
      - postgres
    networks:
      - ticket-reservation
    restart: on-failure
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certificate.crt:/server/server.crt:ro
      - ./nginx/private.key:/server/server.key:ro
      - ./nginx/digital_clock_web:/server/web:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - ticket-reservation
    depends_on:
      - api
    restart: always
  redis:
    image: redis:6-alpine
    security_opt:
      - no-new-privileges
    ports:
      - 6379:${REDIS_PORT:-6379}
    networks:
      - ticket-reservation
networks:
  ticket-reservation: